"""Object storage for meeting recordings.

Audio never goes into Postgres. Two backends behind one interface:

* ``S3Storage`` — any S3-compatible bucket (Railway Buckets, AWS S3,
  Cloudflare R2). Buckets are private; objects are only reachable through
  short-lived presigned URLs handed out by authenticated endpoints.
* ``LocalStorage`` — a directory on disk, for development. Files are only
  served through the authenticated API (no static file route).

Keys are generated by the app (``recordings/<meeting>/<recording>.<ext>``) —
never derived from user input — so they can't escape the bucket/directory.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import BinaryIO, Protocol

from app.core.config import get_settings


class StorageError(Exception):
    pass


class ObjectStorage(Protocol):
    name: str

    def put(self, key: str, fileobj: BinaryIO, content_type: str) -> None: ...

    def delete(self, key: str) -> None: ...

    def presigned_url(self, key: str, *, download_name: str | None = None) -> str | None:
        """A time-limited URL, or None when the backend can't produce one
        (the API then streams the file itself)."""
        ...

    def open(self, key: str) -> BinaryIO: ...

    def local_path(self, key: str) -> Path | None: ...


class LocalStorage:
    name = "local"

    def __init__(self, root: str) -> None:
        self.root = Path(root).resolve()

    def _path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        if self.root not in path.parents:
            raise StorageError("Invalid storage key")
        return path

    def put(self, key: str, fileobj: BinaryIO, content_type: str) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "wb") as out:
            shutil.copyfileobj(fileobj, out)

    def delete(self, key: str) -> None:
        try:
            os.remove(self._path(key))
        except FileNotFoundError:
            pass

    def presigned_url(self, key: str, *, download_name: str | None = None) -> str | None:
        return None

    def open(self, key: str) -> BinaryIO:
        try:
            return open(self._path(key), "rb")
        except FileNotFoundError as exc:
            raise StorageError("Recording file not found") from exc

    def local_path(self, key: str) -> Path | None:
        return self._path(key)


class S3Storage:
    name = "s3"

    def __init__(self) -> None:
        import boto3
        from botocore.config import Config

        settings = get_settings()
        if not (settings.s3_bucket and settings.s3_access_key_id and settings.s3_secret_access_key):
            raise StorageError("S3 storage is selected but S3_BUCKET / S3 credentials are not set")
        self.bucket = settings.s3_bucket
        self.presign_seconds = settings.s3_presign_seconds
        self.client = boto3.client(
            "s3",
            endpoint_url=settings.s3_endpoint_url or None,
            region_name=settings.s3_region or None,
            aws_access_key_id=settings.s3_access_key_id,
            aws_secret_access_key=settings.s3_secret_access_key,
            config=Config(
                signature_version="s3v4",
                s3={"addressing_style": "path" if settings.s3_force_path_style else "auto"},
            ),
        )

    def put(self, key: str, fileobj: BinaryIO, content_type: str) -> None:
        try:
            self.client.upload_fileobj(fileobj, self.bucket, key, ExtraArgs={"ContentType": content_type})
        except Exception as exc:  # botocore raises a zoo of types
            raise StorageError(f"Upload to object storage failed: {type(exc).__name__}") from exc

    def delete(self, key: str) -> None:
        try:
            self.client.delete_object(Bucket=self.bucket, Key=key)
        except Exception as exc:
            raise StorageError(f"Delete from object storage failed: {type(exc).__name__}") from exc

    def presigned_url(self, key: str, *, download_name: str | None = None) -> str | None:
        params = {"Bucket": self.bucket, "Key": key}
        if download_name:
            params["ResponseContentDisposition"] = f'attachment; filename="{download_name}"'
        return self.client.generate_presigned_url("get_object", Params=params, ExpiresIn=self.presign_seconds)

    def open(self, key: str) -> BinaryIO:
        try:
            return self.client.get_object(Bucket=self.bucket, Key=key)["Body"]
        except Exception as exc:
            raise StorageError(f"Read from object storage failed: {type(exc).__name__}") from exc

    def local_path(self, key: str) -> Path | None:
        return None


_storage: ObjectStorage | None = None


def get_storage() -> ObjectStorage:
    global _storage
    if _storage is None:
        settings = get_settings()
        if settings.storage_backend == "s3":
            _storage = S3Storage()
        elif settings.storage_backend == "local":
            _storage = LocalStorage(settings.storage_local_dir)
        else:
            raise StorageError(f"Unknown STORAGE_BACKEND {settings.storage_backend!r}")
    return _storage


def set_storage(storage: ObjectStorage | None) -> None:
    """Test hook."""
    global _storage
    _storage = storage
