"""add location verification fields

Revision ID: 6cd525cc3300
Revises: ad9c882e6223
Create Date: 2026-09-19 00:51:12.852708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6cd525cc3300'
down_revision: Union[str, None] = 'ad9c882e6223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('formatted_address', sa.String(length=1000), nullable=True))
    op.add_column('locations', sa.Column('confidence', sa.String(length=20), nullable=True))
    op.add_column('locations', sa.Column('verification_notes', sa.String(length=1000), nullable=True))
    op.add_column('locations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'updated_at')
    op.drop_column('locations', 'created_at')
    op.drop_column('locations', 'verification_notes')
    op.drop_column('locations', 'confidence')
    op.drop_column('locations', 'formatted_address')
    # ### end Alembic commands ###
