"""add is_planner_generated to meetings

Revision ID: 84ab1f77445b
Revises: 6cd525cc3300
Create Date: 2026-09-19 02:28:33.634813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '84ab1f77445b'
down_revision: Union[str, None] = '6cd525cc3300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing meetings predate this flag and were all created directly
    # (not by the auto-planner), so they correctly default to False.
    op.add_column(
        'meetings',
        sa.Column('is_planner_generated', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('meetings', 'is_planner_generated', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'is_planner_generated')
    # ### end Alembic commands ###
