export const MAPPABLE_FIELD_LABELS: Record<string, string> = {
  company_name: "Company name *",
  legal_name: "Legal name",
  industry: "Industry",
  website: "Website",
  phone: "Phone",
  email: "Email",
  employee_count: "Employee count",
  address_line_1: "Address",
  city: "City",
  state: "State",
  postal_code: "ZIP / postal code",
  country: "Country",
  contact_first_name: "Contact first name",
  contact_last_name: "Contact last name",
  contact_full_name: "Contact full name",
  contact_title: "Contact job title",
  contact_email: "Contact email",
  contact_phone: "Contact phone",
  contact_linkedin: "Contact LinkedIn",
};
